apiVersion: v1
kind: Pod
metadata:
    name: db-noticias
    labels:
        app: db-noticias
spec:
    containers:
        - name: db-noticias-container
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-configmap
         #env:
         #  - name: MYSQL_ROOT_PASSWORD
         #    valueFrom: 
         #      configMapKeyRef:
         #        name: db-configmap
         #        key: MYSQL_ROOT_PASSWORD
         

         # Estas variáveis devem ser devinidas em outro arquivo,
         # com outro service, o configMap, para tornar este arquivo
         # mais portável

         # Importando variáveis do configMap uma a uma:

         #env:
         #- name: "MYSQL_ROOT_PASSWORD"  
         #  value: "q1w2e3r4"
         #- name: "MYSQL_DATABASE"
         #  value: "emrpesa"
         #- name: "MYSQL_PASSWORD"
         #  value: "q1w2e3r4"
         

