apiVersion: v1
kind: Service
metadata:
    name: svc-portal-noticias
spec:
    type: NodePort
    ports:
        - port: 80
          #o nodePort e o targetPort não forem declarados,
          #serão iguais ao valor do port
          nodePort: 30000 
    selector:
        app: portal-noticias